# Generated by Django 6.1 on 2026-09-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('SUCCESS', 'success'), ('FAILURE', 'failure')], default='PENDING', max_length=20),
        ),
    ]
